// <auto-generated />
using BCUniversity.Infrastructure.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BCUniversity.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20190420063829_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("uni")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.LectureDataModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("SubjectId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("lecture");

                    b.HasData(
                        new
                        {
                            Id = "d33ea94a-b2c7-435a-ad8b-0b75f33189cc",
                            Name = "Lecture 1",
                            SubjectId = "81b6ec83-e8b4-4ad5-8893-1f763200393d"
                        },
                        new
                        {
                            Id = "9735bdc7-79ca-4728-b2dc-ba4ab4f70d1d",
                            Name = "Lecture 2",
                            SubjectId = "a9a5db84-7de3-40a0-b464-a9cfd7c60a06"
                        },
                        new
                        {
                            Id = "86b20947-e7f2-4c25-845b-652b74c0a103",
                            Name = "Lecture 3",
                            SubjectId = "a9a5db84-7de3-40a0-b464-a9cfd7c60a06"
                        },
                        new
                        {
                            Id = "ca24c626-873b-4d27-8e30-bfd26e760b13",
                            Name = "Lecture 4",
                            SubjectId = "9ee3209c-2333-4cd1-ae13-84039e5b8e35"
                        });
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.Relationships.LectureTheatreLink", b =>
                {
                    b.Property<string>("LectureId");

                    b.Property<string>("TheatreId");

                    b.Property<int>("DayOfWeek");

                    b.Property<int>("EndHour");

                    b.Property<int>("StartHour");

                    b.HasKey("LectureId", "TheatreId");

                    b.HasIndex("LectureId")
                        .IsUnique();

                    b.HasIndex("TheatreId");

                    b.ToTable("lecture_theatre_relationship");

                    b.HasData(
                        new
                        {
                            LectureId = "d33ea94a-b2c7-435a-ad8b-0b75f33189cc",
                            TheatreId = "180c5352-2a8b-4941-9728-2790ab5e15af",
                            DayOfWeek = 1,
                            EndHour = 18,
                            StartHour = 10
                        },
                        new
                        {
                            LectureId = "9735bdc7-79ca-4728-b2dc-ba4ab4f70d1d",
                            TheatreId = "180c5352-2a8b-4941-9728-2790ab5e15af",
                            DayOfWeek = 2,
                            EndHour = 16,
                            StartHour = 14
                        },
                        new
                        {
                            LectureId = "86b20947-e7f2-4c25-845b-652b74c0a103",
                            TheatreId = "180c5352-2a8b-4941-9728-2790ab5e15af",
                            DayOfWeek = 3,
                            EndHour = 12,
                            StartHour = 10
                        },
                        new
                        {
                            LectureId = "ca24c626-873b-4d27-8e30-bfd26e760b13",
                            TheatreId = "dd01bbdf-26b8-43db-8d4c-7d394fbddaac",
                            DayOfWeek = 5,
                            EndHour = 11,
                            StartHour = 10
                        });
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.Relationships.SubjectStudentLink", b =>
                {
                    b.Property<string>("SubjectId");

                    b.Property<string>("StudentId");

                    b.HasKey("SubjectId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("subject_student_relationship");
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.StudentDataModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            Id = "c15cef22-35db-4ccb-a725-8bb127b8dcb1",
                            Name = "Student 1"
                        },
                        new
                        {
                            Id = "2ea37cfc-72b5-4898-a768-b20f9aa354b9",
                            Name = "Student 2"
                        },
                        new
                        {
                            Id = "7bb294f6-a199-4197-bdbd-f010283e7a74",
                            Name = "Student 3"
                        });
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.SubjectDataModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("subject");

                    b.HasData(
                        new
                        {
                            Id = "81b6ec83-e8b4-4ad5-8893-1f763200393d",
                            Name = "Subject 1"
                        },
                        new
                        {
                            Id = "a9a5db84-7de3-40a0-b464-a9cfd7c60a06",
                            Name = "Subject 2"
                        },
                        new
                        {
                            Id = "9ee3209c-2333-4cd1-ae13-84039e5b8e35",
                            Name = "Subject 3"
                        });
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.TheatreDataModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("theatre");

                    b.HasData(
                        new
                        {
                            Id = "180c5352-2a8b-4941-9728-2790ab5e15af",
                            Capacity = 10,
                            Name = "Theatre 1"
                        },
                        new
                        {
                            Id = "dd01bbdf-26b8-43db-8d4c-7d394fbddaac",
                            Capacity = 1,
                            Name = "Theatre 2"
                        });
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.LectureDataModel", b =>
                {
                    b.HasOne("BCUniversity.Infrastructure.DataModel.SubjectDataModel", "Subject")
                        .WithMany("Lectures")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.Relationships.LectureTheatreLink", b =>
                {
                    b.HasOne("BCUniversity.Infrastructure.DataModel.LectureDataModel", "Lecture")
                        .WithOne("LectureTheatreLink")
                        .HasForeignKey("BCUniversity.Infrastructure.DataModel.Relationships.LectureTheatreLink", "LectureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BCUniversity.Infrastructure.DataModel.TheatreDataModel", "Theatre")
                        .WithMany("Lectures")
                        .HasForeignKey("TheatreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BCUniversity.Infrastructure.DataModel.Relationships.SubjectStudentLink", b =>
                {
                    b.HasOne("BCUniversity.Infrastructure.DataModel.StudentDataModel", "Student")
                        .WithMany("SubjectLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BCUniversity.Infrastructure.DataModel.SubjectDataModel", "Subject")
                        .WithMany("StudentLinks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
