version: '3'

services:
  db:
    image: postgres:11.2
    ports:
      - 5432:5432
    env_file:
      - dev.env
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /app
    entrypoint: "./seedAndRun.sh"
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - dev.env